#!/bin/sh
set -eu

exec runuser -u www-data -- php -r '
$socket = @stream_socket_client(
    "tcp://127.0.0.1:8081", $errorCode, $errorMessage, 2);
if ($socket === false) exit(1);
fwrite($socket, "GET /healthz.php HTTP/1.0\r\nHost: localhost\r\nConnection: close\r\n\r\n");
$status = fgets($socket);
fclose($socket);
exit(is_string($status) && preg_match("~^HTTP/[0-9.]+ 204 ~", $status) ? 0 : 1);
'
