**

!tinyfilemanager.php
!translation.json
!LICENSE
!contrib/
!contrib/container/
!contrib/container/apache.conf
!contrib/container/healthz.php
!contrib/container/php.ini
!contrib/afs/
!contrib/afs/Dockerfile
!contrib/afs/LICENSE.mod-auth-gssapi
!contrib/afs/LICENSE.mod-waklog
!contrib/afs/afs-entrypoint
!contrib/afs/afs-preflight.c
!contrib/afs/container-healthcheck-afs
!contrib/afs/patches/
!contrib/afs/patches/**
!contrib/afs/ports.conf
!contrib/afs/sources.lock
!contrib/afs/tinyfilemanager-afs.conf
!contrib/afs/validate-config.php
!contrib/afs/waklog.load

# Runtime inputs and credentials must never enter the build context.
**/config.php
**/*.key
**/*.keytab
**/*.pem
**/secrets/**
**/clientcaches/**
**/*.ccache
