ServerRoot "/etc/httpd"
DefaultRuntimeDir "/run/httpd"
PidFile "/run/httpd/httpd.pid"

Listen 8443
Listen 127.0.0.1:8081

Include conf.modules.d/*.conf

User apache
Group apache
ServerName localhost
ServerAdmin root@localhost
ServerTokens Prod
ServerSignature Off
TraceEnable Off
FileETag None
EnableSendfile Off
DirectoryIndex index.php

ErrorLog /dev/stderr
LogLevel warn
LogFormat "%a %t \"%m %U %H\" %>s %b" tinyfilemanager_auristor

<IfModule mime_module>
    TypesConfig /etc/mime.types
</IfModule>

<Directory "/">
    AllowOverride None
    Require all denied
</Directory>

Include /etc/httpd/conf.d/tinyfilemanager-hardening.conf
Include /etc/httpd/conf.d/tinyfilemanager-auristor-vhosts.conf
